## Predicting Backorders

        Backorder:A backorder generally indicates that customer demand for a product or service exceeds a company’s capacity to supply it. Product backorder may be the result of strong sales performance (e.g. the product is in such high demand that production cannot keep up with sales). However, backorders can upset consumers, lead to canceled orders and decreased customer loyalty. Companies want to avoid backorders, but also avoid overstocking every product (leading to higher inventory costs). Machine learning can identify patterns related to backorders before customers order. Production can then adjust to minimize delays while customer service can provide accurate dates to keep customers informed and happy. The predictive analytics approach enables the maximum product to get in the hands of customers at the lowest cost to the organization.
## Problem Statement
* In supply chain systems, material backorders are common, impacting service levels and inventory effectiveness.
* This project aims to train classifiers to predict future backordered products and generate predictions for a test set.

## Data fields

Data Fields
* sku: SKU code
* nationalinv: Current inventory level of component
* leadtime: Transit time
*  in transit qty: Quantity in transit
*  forecastxmonth: Forecast sales for the next 3, 6, 9 months
*  salesxmonth: Sales quantity for the prior 1, 3, 6, 9 months
* minbank: Minimum recommended amount in stock
* potentialissue: Indicator variable noting potential issue with item
* pieces past due: Parts overdue from source
* perfxmonthsavg: Source performance in the last 6 and 12 months
* localboqty: Amount of stock orders overdue
* X17-X22: General Risk Flags
*  wentonbackorder: Product went on backorder (target variable)

# Backorder Classfication  ML   Project
**Life cycle of Machine learning Project**

* Understanding the Problem Statement
* Data Collection
* Exploratory data analysis
* Data Cleaning
* Data Pre-Processing
* Model Training 
* Choose best model

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=  pd.read_csv("Back_order_train.csv")

C:\Users\himal\AppData\Local\Temp\ipykernel_29288\2247070370.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df=  pd.read_csv("Back_order_train.csv")

In [4]:
df.head()

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,1026827,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,No,No,No,Yes,No,No
1,1043384,2.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.99,0.99,0.0,No,No,No,Yes,No,No
2,1043696,2.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No
3,1043852,7.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.10,0.13,0.0,No,No,No,Yes,No,No
4,1044048,8.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No